# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DurationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#-----------------------------------------------------------------------
# DurationDialog.py
#
# Dialog box that opens when duration time set to custom in drop down
#-----------------------------------------------------------------------

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DurationDialog(object):

    def setupUi(self, Duration):
        Duration.setObjectName("Duration")
        Duration.setEnabled(True)
        Duration.resize(340, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Duration.sizePolicy().hasHeightForWidth())
        Duration.setSizePolicy(sizePolicy)
        Duration.setMinimumSize(QtCore.QSize(0, 130))
        Duration.setStyleSheet(
            "QSpinBox::up-button { width: 25; height: 20}\n"
            "QSpinBox::down-button { width: 25; height: 20}")
        Duration.setSizeGripEnabled(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Duration)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.select_duration = QtWidgets.QGroupBox(Duration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.select_duration.sizePolicy().hasHeightForWidth())
        self.select_duration.setSizePolicy(sizePolicy)
        self.select_duration.setObjectName("select_duration")
        self.gridLayout = QtWidgets.QGridLayout(self.select_duration)
        self.gridLayout.setObjectName("gridLayout")
        self.hour_spinbox = QtWidgets.QSpinBox(self.select_duration)
        self.hour_spinbox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.hour_spinbox.sizePolicy().hasHeightForWidth())
        self.hour_spinbox.setSizePolicy(sizePolicy)
        self.hour_spinbox.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hour_spinbox.setFont(font)
        self.hour_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.hour_spinbox.setObjectName("hour_spinbox")
        self.gridLayout.addWidget(self.hour_spinbox, 0, 0, 1, 1)
        self.hours = QtWidgets.QLabel(self.select_duration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed,
                                           QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.hours.sizePolicy().hasHeightForWidth())
        self.hours.setSizePolicy(sizePolicy)
        self.hours.setScaledContents(False)
        self.hours.setObjectName("hours")
        self.gridLayout.addWidget(self.hours, 0, 1, 1, 1)
        self.minute_spinbox = QtWidgets.QSpinBox(self.select_duration)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding,
                                           QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.minute_spinbox.sizePolicy().hasHeightForWidth())
        self.minute_spinbox.setSizePolicy(sizePolicy)
        self.minute_spinbox.setMinimumSize(QtCore.QSize(100, 45))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.minute_spinbox.setFont(font)
        self.minute_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.minute_spinbox.setObjectName("minute_spinbox")
        self.gridLayout.addWidget(self.minute_spinbox, 0, 2, 1, 1)
        self.minutes = QtWidgets.QLabel(self.select_duration)
        self.minutes.setObjectName("minutes")
        self.gridLayout.addWidget(self.minutes, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.select_duration)
        self.cancel_ok = QtWidgets.QDialogButtonBox(Duration)
        self.cancel_ok.setOrientation(QtCore.Qt.Horizontal)
        self.cancel_ok.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel
                                          | QtWidgets.QDialogButtonBox.Ok)
        self.cancel_ok.setObjectName("cancel_ok")
        self.verticalLayout.addWidget(self.cancel_ok)
        self.hours.setBuddy(self.hour_spinbox)
        self.minutes.setBuddy(self.minute_spinbox)

        self.retranslateUi(Duration)
        self.cancel_ok.accepted.connect(Duration.accept)  # type: ignore
        self.cancel_ok.rejected.connect(Duration.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Duration)
        Duration.setTabOrder(self.hour_spinbox, self.minute_spinbox)

    def retranslateUi(self, Duration):
        _translate = QtCore.QCoreApplication.translate
        Duration.setWindowTitle(_translate("Duration", "Dialog"))
        self.select_duration.setTitle(
            _translate("Duration", "Select a duration:"))
        self.hours.setText(_translate("Duration", "hr(s)"))
        self.minutes.setText(_translate("Duration", "min(s)"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Duration = QtWidgets.QDialog()
    ui = Ui_DurationDialog()
    ui.setupUi(Duration)
    Duration.show()
    sys.exit(app.exec_())
